### ISSUE TITLE
Unable to load Mesh Files into Moveit Scene

### ISSUE THREAD

**Issue by acbuynak** [OSU-AIMS/paper-glider#1]
Having issues loading mesh files into the Moveit Scene Planner. 
Files formats accepted include: STL and DAE.   Both attempted.

Code:
` self.scene.add_mesh(self.glider_name, glider_pose, filename="$(find paper-glider)/meshes/glider-model.stl", size=(1,1,1))`

Traceback:
```
Traceback (most recent call last):
  File "/home/a/_DEV/ws_paperGlider/src/paper-glider/scripts/paper-glider.py", line 488, in <module>
    main()
  File "/home/a/_DEV/ws_paperGlider/src/paper-glider/scripts/paper-glider.py", line 464, in main
    robot.add_glider()
  File "/home/a/_DEV/ws_paperGlider/src/paper-glider/scripts/paper-glider.py", line 406, in add_glider
    self.scene.add_mesh(self.glider_name, glider_pose, filename="$(find paper-glider)/meshes/glider-model.stl", size=(1,1,1))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/moveit_commander/planning_scene_interface.py", line 98, in add_mesh
    co = self.__make_mesh(name, pose, filename, size)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/moveit_commander/planning_scene_interface.py", line 244, in __make_mesh
    scene = pyassimp.load(filename)
  File "/usr/lib/python2.7/dist-packages/pyassimp/core.py", line 318, in load
    raise AssimpError('Could not import file!')
pyassimp.errors.AssimpError: Could not import file!
```

**Comment by acbuynak** [comment]
Source Code for Moveit Commander
http://docs.ros.org/en/melodic/api/moveit_commander/html/classmoveit__commander_1_1planning__scene__interface_1_1PlanningSceneInterface.html#af57e2069f27f667144fa721c7ef8e5b6

Tutorial by Danfoa: Adding Dynamic Mesh Collision Objects (C++)
https://github.com/Danfoa/invite-robotics/wiki/Tutorial---Simulation-Scene-Objects

Attaching Object to Robot
http://docs.ros.org/en/indigo/api/moveit_tutorials/html/doc/pr2_tutorials/planning/src/doc/planning_scene_ros_api_tutorial.html#attach-an-object-to-the-robot

**Comment by acbuynak** [comment]
Using MoveIt Planning Plugin.. Able to Scene objects using "Scene Objects" Tab > Add/Remove Scene Objects > "From Mesh File"

![image](https://user-images.githubusercontent.com/44533530/98627017-27769180-22e1-11eb-8a81-7fb09fd2ed9d.png)

**Comment by ADIMADE** [comment]
I am facing the same issue:( Have you found a solution allready?
